### ISSUE TITLE
kubernetes cluster creation 

### ISSUE THREAD

**Issue by rgrishigajra** [airavata-courses/HogwartsRejects#153]
Failing in terraform newest version

**Comment by gkiran292** [comment]
Done
Details - https://github.com/airavata-courses/HogwartsRejects/wiki/Setting-up-your-kubernetes-cluster

**Comment by gkiran292** [comment]
With the terraform newer version I am having problems with integration and currently, I am in contact with the developer please follow this thread for continued information. This is the issue of terraform and not this project.
Link - https://github.com/terraform-providers/terraform-provider-openstack/issues/938
