### ISSUE TITLE
Node js not connecting to dockerized go lang service

### ISSUE THREAD

**Issue by gkiran292** [airavata-courses/HogwartsRejects#17]
Connection refused error with node js and dockerized golang service

**Comment by rgrishigajra** [comment]
Worked on the Golang docker and node Js connection with Fron End. The code in API gateway, node had some bugs and Golang had CORS error. Solved in lastest commit to branch feature-api
[https://github.com/airavata-courses/HogwartsRejects/tree/feature-api-gw](url).

**Comment by rgrishigajra** [comment]
Node JS is working with front end too now, showing the current weather on the landing page. Closing issue as resolved.
