### ISSUE TITLE
Dockerization of Nginx and Node JS

### ISSUE THREAD

**Issue by gkiran292** [airavata-courses/HogwartsRejects#87]
Dockerization of Nginx

**Comment by rgrishigajra** [comment]
linked with issue 
https://github.com/airavata-courses/HogwartsRejects/issues/36
closing as solved

**Comment by gkiran292** [comment]
Dockerization has been taken care of in assignment 1 if you need to execute the assignment 1 please follow below guidelines
Link - https://github.com/airavata-courses/HogwartsRejects/wiki/Milestone-1
